# Imports the 'os' module to interact with the operating system.
import os  

# This line would clean the case directory by removing generated files from a previous simulation.
os.system('foamCleanCase')  

# Runs the OpenFOAM utility 'gmshToFoam' to convert the mesh generated by gmsh to OpenFOAM format.
# The msh file must be already placed in the directory from the geo file, from gmsh.
# This command creates a mesh that OpenFOAM can read.
# The mesh (named polymesh) is created in the constant folder.
os.system('gmshToFoam tJunction.msh')

# The converted mesh needs to be edited. 
# Here we use the OpenFOAM utility 'foamDictionary' to change the type of the boundaries.
# When the mesh is converted from gmsh, all entries are 'patch', which is suitable for inlet and outlet.
# We need to change the types of the empty faces and wall faces. 
os.system('foamDictionary constant/polyMesh/boundary -entry entry0/frontAndBack/type -set "empty"')
os.system('foamDictionary constant/polyMesh/boundary -entry entry0/walls/type -set "wall"')

# Command to decompose the domain to run in parallel.
os.system('decomposePar')

# Runs the OpenFOAM solver 'foamRun' in parallel.
os.system('mpirun -np 4 foamRun -parallel')

# Reconstructs the simulation results from the decomposed
# domain.
os.system('reconstructPar')

# Opens the case in ParaView using 'paraFoam' for visualization.
#os.system('paraFoam')

# Plot the flow rate evolution in each outlet. 
os.system('python3 plotPatchFlowRateOutlet1Outlet2.py')
