# Imports the 'os' module to interact with the operating system.
import os  

from scriptRunFunctions import *

# This line would clean the case directory by removing generated files from a previous simulation.
os.system('foamCleanCase')  

# Runs the OpenFOAM utility 'gmshToFoam' to convert the mesh generated by gmsh to OpenFOAM format.
# The msh file must be already placed in the directory from the geo file, from gmsh.
# This command creates a mesh that OpenFOAM can read.
# The mesh (named polymesh) is created in the constant folder.
os.system('gmshToFoam tJunction.msh')

# The converted mesh needs to be edited. 
# Here we use the OpenFOAM utility 'foamDictionary' to change the type of the boundaries.
# When the mesh is converted from gmsh, all entries are 'patch', which is suitable for inlet and outlet.
# We need to change the types of the empty faces and wall faces. 
os.system('foamDictionary constant/polyMesh/boundary -entry entry0/frontAndBack/type -set "empty"')
os.system('foamDictionary constant/polyMesh/boundary -entry entry0/walls/type -set "wall"')

# Creates baffles from existing patches in the mesh.
os.system('createBaffles')

# The command createBaffles create a new mesh and writes it in 
# a new time folder. We need to copy the initial condition files
# from folder 0 to this new folder.
# This function copies the files from folder 0 to the last
# folder.
copy_field_files(
    '0',
    max((f for f in os.listdir('.') if os.path.isdir(f) and is_time_folder(f)), key=lambda x: float(x)),
    ['U', 'p', 'T', 'CH4', 'CO2', 'N2']
)

# Runs the OpenFOAM solver 'foamRun'.
os.system('foamRun')  

# Opens the case in ParaView using 'paraview' for visualization.
#os.system('touch foam.foam')
#os.system('paraview foam.foam')
